In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/SalesJan2009.csv')

In [3]:
df.head()

,Transaction_date,Product,Price,Payment_Type,Name,City,State,Country,Account_Created,Last_Login,Latitude,Longitude
0,1/2/09 6:17,Product1,1200,Mastercard,carolina,Basildon,England,United Kingdom,1/2/09 6:00,1/2/09 6:08,51.500000,-1.116667
1,1/2/09 4:53,Product1,1200,Visa,Betina,Parkville,MO,United States,1/2/09 4:42,1/2/09 7:49,39.195000,-94.681940
2,1/2/09 13:08,Product1,1200,Mastercard,Federica e Andrea,Astoria,OR,United States,1/1/09 16:21,1/3/09 12:32,46.188060,-123.830000
3,1/3/09 14:44,Product1,1200,Visa,Gouya,Echuca,Victoria,Australia,9/25/05 21:13,1/3/09 14:22,-36.133333,144.750000
4,1/4/09 12:56,Product2,3600,Visa,Gerd W,Cahaba Heights,AL,United States,11/15/08 15:47,1/4/09 12:45,33.520560,-86.802500

In [54]:
prom_ventas_pais = df.groupby('Country')['Price'].mean().reset_index()

In [51]:
pais_ciudad_sum = df.groupby(['Country', 'City'])['Price'].sum().reset_index()

In [62]:
datos = {'Pais': [], 'Promedio': [], 'Ciudades': []}
for (pais, prom) in zip(prom_ventas_pais['Country'], prom_ventas_pais['Price']):
  print("Promedio ventas de ", pais, ":", prom)
  ciudades = pais_ciudad_sum[(pais_ciudad_sum['Country'] == pais) & (pais_ciudad_sum['Price'] >= prom)]['City']

  salida = []
  for ciudad in ciudades:
    salida.append(ciudad.strip())

  print("Ciudades con ventas >= prom :", ",".join(salida))
  print("----------------------------------------------")

  datos['Pais'].append(pais)
  datos['Promedio'].append(prom)
  datos['Ciudades'].append(salida)

Promedio ventas de  Argentina : 1200.0
Ciudades con ventas >= prom : Ayacucho
----------------------------------------------
Promedio ventas de  Australia : 1705.2631578947369
Ciudades con ventas >= prom : Avalon,Brisbane,Bunbury,Burpengary,Gisborne,Melbourne,Mona Vale,Perth,Scamander,Sydney
----------------------------------------------
Promedio ventas de  Austria : 1542.857142857143
Ciudades con ventas >= prom : Neustift am Walde,WalcProduct3ee
----------------------------------------------
Promedio ventas de  Bahrain : 1200.0
Ciudades con ventas >= prom : Al 'Adliyah
----------------------------------------------
Promedio ventas de  Belgium : 1500.0
Ciudades con ventas >= prom : Brussels,Bruxelles
----------------------------------------------
Promedio ventas de  Bermuda : 1200.0
Ciudades con ventas >= prom : Hamilton
----------------------------------------------
Promedio ventas de  Brazil : 2460.0
Ciudades con ventas >= prom : Campinas
----------------------------------------------
Promedio ventas de  Bulgaria : 1200.0
Ciudades con ventas >= prom : Zagore
----------------------------------------------
Promedio ventas de  Canada : 1642.1052631578948
Ciudades con ventas >= prom : Calgary,Carcross,Edmonton,Kelowna,Mission,Montreal,North Bay,Okotoks,Ottawa,Powell River,Prince Albert,Saskatoon,Toronto,Vancouver
----------------------------------------------
Promedio ventas de  Cayman Isls : 1200.0
Ciudades con ventas >= prom : George Town
----------------------------------------------
Promedio ventas de  China : 1200.0
Ciudades con ventas >= prom : Taicheng
----------------------------------------------
Promedio ventas de  Costa Rica : 1200.0
Ciudades con ventas >= prom : Santa Barbaraa
----------------------------------------------
Promedio ventas de  Czech Republic : 2000.0
Ciudades con ventas >= prom : Prague
----------------------------------------------
Promedio ventas de  Denmark : 1200.0
Ciudades con ventas >= prom : Brondby Strand,Charlottenlund,Hellerup,Helsingor,Holte,Kjobenhavn,Klampenborg,Kobenhavn,Laasby,Lyngby,Nakskov,Rungsted,Soro
----------------------------------------------
Promedio ventas de  Dominican Republic : 1200.0
Ciudades con ventas >= prom : Santo Domingo City
----------------------------------------------
Promedio ventas de  Finland : 1200.0
Ciudades con ventas >= prom : Kuopio,Lahti
----------------------------------------------
Promedio ventas de  France : 1966.6666666666667
Ciudades con ventas >= prom : Biot,Ferney-Voltaire,Paris,Rennes,Saint-Cergues
----------------------------------------------
Promedio ventas de  Germany : 1680.0
Ciudades con ventas >= prom : Braunschweig,Donauworth,Munich,Stuttgart,Telgte,Wiesbaden
----------------------------------------------
Promedio ventas de  Greece : 1200.0
Ciudades con ventas >= prom : Athina
----------------------------------------------
Promedio ventas de  Guatemala : 1200.0
Ciudades con ventas >= prom : Atlantida
----------------------------------------------
Promedio ventas de  Hong Kong : 1200.0
Ciudades con ventas >= prom : Hong Kong
----------------------------------------------
Promedio ventas de  Hungary : 1200.0
Ciudades con ventas >= prom : Budaors,Chepel,Kecskemet
----------------------------------------------
Promedio ventas de  Iceland : 1200.0
Ciudades con ventas >= prom : Thorlakshofn
----------------------------------------------
Promedio ventas de  India : 1200.0
Ciudades con ventas >= prom : Gurgaon,Hyderabad
----------------------------------------------
Promedio ventas de  Ireland : 1426.530612244898
Ciudades con ventas >= prom : Ballincollig,Castleknock,Clondalkin,Clontarf,Cork,Navan,Rathfarnham
----------------------------------------------
Promedio ventas de  Israel : 1200.0
Ciudades con ventas >= prom : Tel Aviv
----------------------------------------------
Promedio ventas de  Italy : 2520.0
Ciudades con ventas >= prom : Cagliari,Lipari,Milano,Ponte San Nicolo
----------------------------------------------
Promedio ventas de  Japan : 1200.0
Ciudades con ventas >= prom : Setagaya,Tokyo
----------------------------------------------
Promedio ventas de  Jersey : 1200.0
Ciudades con ventas >= prom : Gorey
----------------------------------------------
Promedio ventas de  Kuwait : 1200.0
Ciudades con ventas >= prom : Mushrif
----------------------------------------------
Promedio ventas de  Latvia : 1200.0
Ciudades con ventas >= prom : Vecmilgravis
----------------------------------------------
Promedio ventas de  Luxembourg : 1200.0
Ciudades con ventas >= prom : Gasperich
----------------------------------------------
Promedio ventas de  Malaysia : 1200.0
Ciudades con ventas >= prom : Kuala Lumpur
----------------------------------------------
Promedio ventas de  Malta : 2400.0
Ciudades con ventas >= prom : San Pawl tat-Targa
----------------------------------------------
Promedio ventas de  Mauritius : 3600.0
Ciudades con ventas >= prom : Black River
----------------------------------------------
Promedio ventas de  Moldova : 1200.0
Ciudades con ventas >= prom : Bubuieci
----------------------------------------------
Promedio ventas de  Monaco : 1200.0
Ciudades con ventas >= prom : Monaco,Monte-Carlo
----------------------------------------------
Promedio ventas de  Netherlands : 2031.8181818181818
Ciudades con ventas >= prom : Amsterdam,Den Haag,Ede,Hilversum,Oegstgeest,Utrecht
----------------------------------------------
Promedio ventas de  New Zealand : 1200.0
Ciudades con ventas >= prom : Auckland,Hawera,New Plymouth City,Torbay,Waiau Pa,Waiwera
----------------------------------------------
Promedio ventas de  Norway : 1350.0
Ciudades con ventas >= prom : Oslo,Stavanger
----------------------------------------------
Promedio ventas de  Philippines : 1200.0
Ciudades con ventas >= prom : Baluan,Borja
----------------------------------------------
Promedio ventas de  Poland : 1200.0
Ciudades con ventas >= prom : Gdansk,Pruszkow
----------------------------------------------
Promedio ventas de  Romania : 1200.0
Ciudades con ventas >= prom : Voluntari
----------------------------------------------
Promedio ventas de  Russia : 3600.0
Ciudades con ventas >= prom : Tsaritsyno
----------------------------------------------
Promedio ventas de  South Africa : 2460.0
Ciudades con ventas >= prom : Pietermaritzburg
----------------------------------------------
Promedio ventas de  South Korea : 1200.0
Ciudades con ventas >= prom : Songnae-dong
----------------------------------------------
Promedio ventas de  Spain : 1400.0
Ciudades con ventas >= prom : Barcelona,Gava,Madrid
----------------------------------------------
Promedio ventas de  Sweden : 1753.8461538461538
Ciudades con ventas >= prom : Lidingo,Malmo,Nacka,Norrkoping
----------------------------------------------
Promedio ventas de  Switzerland : 2133.3333333333335
Ciudades con ventas >= prom : Balgach,Begnins,Bellinzona,Berikon,Bern,Binningen,Carouge,Geneve,Kloten,Langnau,Lausanne,Trelex,Zug,Zurich
----------------------------------------------
Promedio ventas de  Thailand : 2400.0
Ciudades con ventas >= prom : Ban Khlong Sip
----------------------------------------------
Promedio ventas de  The Bahamas : 1200.0
Ciudades con ventas >= prom : Freeport City,Killarney
----------------------------------------------
Promedio ventas de  Turkey : 1200.0
Ciudades con ventas >= prom : Beykoz,Istanbul,Izmir,Kemerburgaz,Tesvikiye,Zekeriyakoy
----------------------------------------------
Promedio ventas de  Ukraine : 1200.0
Ciudades con ventas >= prom : Irpin'
----------------------------------------------
Promedio ventas de  United Arab Emirates : 2000.0
Ciudades con ventas >= prom : Dubai,Jumeira
----------------------------------------------
Promedio ventas de  United Kingdom : 1440.0
Ciudades con ventas >= prom : Aberdeen,Ashford,Bolton,Edinburgh,Guildford,Huddersfield,Kirriemuir,London,Milton Keynes,New Malden,Oxford,Penclawdd,Reading,Tunbridge Wells,Watford,York
----------------------------------------------
Promedio ventas de  United States : 1594.6004319654428
Ciudades con ventas >= prom : Alexandria,Alpharetta,Anchorage,Ann Arbor,Arlington,Atlanta,Austin,Brooklyn,Buffalo Grove,Cahaba Heights,Cartersburg,Centennial,Chandler,Chicago,Cincinnati,Clyde Hill,Coconut Grove,Cranberry Twp,Davis,Delray Beach,Downingtown,Eagan,Englewood,Fayetteville,Flossmoor,Fort Lauderdale,Fresno,Hilton Head,Houston,Huntington Beach,Irvine,Issaquah,Jacksonville,Joppa,Katy,Kearns,Keller,Killeen,Knoxville,Lafayette,Las Vegas,Los Angeles,Los Gatos,Mableton,Mahopac,Manhattan,Marietta,Miami,Mililani,Minneapolis,Morrison,Nashville,New Rochelle,New York,Norfolk,Olive Branch,Orlando,Overland,Penngrove,Pensacola,Phoenix,Pittsfield,Plantation,Portola Valley,Queen Creek,Reston,Rochester Hills,Rockville,Rogers,Royal Oak,Saint Paul,Salt Lake City,San Anselmo,San Antonio,San Diego,San Francisco,San Jose,San Ramon,Scottsdale,Seattle,Sebastopol,Senatobia,Shreveport,Silver Spring,Sitka,Skaneateles,St Thomas,Staten Island,Sterling,Sunnyvale,Swampscott,Temecula,Tenafly,Valley Center,Vienna,Villanova,Warwick,Washington,Wilmington,Winter Haven
----------------------------------------------

In [63]:
datos_df = pd.DataFrame(datos)

In [64]:
datos_df.to_csv('salida.csv', sep=',')

In [65]:
datos_df.head()

        Pais     Promedio                                           Ciudades
0  Argentina  1200.000000                                         [Ayacucho]
1  Australia  1705.263158  [Avalon, Brisbane, Bunbury, Burpengary, Gisbor...
2    Austria  1542.857143                [Neustift am Walde, WalcProduct3ee]
3    Bahrain  1200.000000                                      [Al 'Adliyah]
4    Belgium  1500.000000                              [Brussels, Bruxelles]